name: Release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref_name }} # v1.2.3のような値をGitタグから取得
    permissions:
      contents: write # リリースノートの作成に必要なパーミッション
    steps:
      - uses: actions/checkout@v4
      - run: | # リリースノートの作成とアセットのアップロード
          gh release create "${VERSION}" --title "${VERSION}" --generate-notes
          gh release upload "${VERSION}" "${RUNNER_TEMP}"/src
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}